# Generated by Django 2.2.3 on 2019-07-14 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('surveys', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='choices',
                to='surveys.Question',
            ),
        )
    ]
